### ISSUE TITLE
No Valid DLL Selected

### ISSUE THREAD

**Issue by Stebulous** [guided-hacking/GuidedHacking-Injector#1]
I'm trying to inject a hack menu into TABG and it says this.

**Comment by GH-Rake** [comment]
Sorry for the late reply, are you using the latest version 3.3?

Make sure the dll is the same architecture, x86 for x86 process and x64 for x64 process

https://guidedhacking.com/resources/guided-hacking-dll-injector.4/history

**Comment by artemking4-Projects** [comment]
Im pretty sure he tries to inject a .net dll to a unity application. TABG is unity, and i guess, hes using a wrong tool to inject

**Comment by GH-Rake** [comment]
> Im pretty sure he tries to inject a .net dll to a unity application. TABG is unity, and i guess, hes using a wrong tool to inject

it's not a mono injector
